apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build-simplewebkv
  namespace: jd001
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--verbosity=info",
            "--log-format=color",
            "--dockerfile=./Dockerfile",
            "--context=git://github.com/jkdihenkar/SimpleWebKV.git#refs/heads/main",
            "--destination=jkdihenkar/simplewebkv:latest"]
    volumeMounts:
    - name: kaniko-secret
      mountPath: "/kaniko/.docker"
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json