version: 2.1

# Describe JOBS

jobs:
  run_tests:
    docker: 
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run:
        name: Install dependencies
        command: |
          pip install --user -r requirements.txt
      - run:
        name: Run Unit Tests
        command: |
          pytest --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

# Workflow

workflows:
  build_test:
    jobs:
      - run_tests

