---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplewebkv
  labels:
    app: simplewebkv
    manifest_type: api
spec:
  selector:
    matchLabels:
      app: simplewebkv
  template:
    metadata:
      name: simplewebkv
      labels:
        app: simplewebkv
    spec:
      containers:
      - image: docker.io/jkdihenkar/simplewebkv
        name: simplewebkv
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
            name: http
        command: ["python"]
        args:  ["./simplekv_server.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: simplewebkv
  labels:
    app: simplewebkv
    manifest_type: svc
spec:
  type: NodePort
  selector:
    app: simplewebkv
  ports:
    - port: 8991
      name: simplewebkv
      targetPort: 5000
      