# SAMPLE TASKRUN
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: testrun
spec:
  taskRef:
    name: run-tests
  resources:
    inputs:
      - name: repo
        resourceRef:
          name: jkdihenkar-simplewebkv