apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: simplewebkv-pipeline-run-1
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers
  pipelineRef:
    name: simplewebkv-ci
  resources:
    - name: git-source
      resourceRef:
        name: simplewebkv-repo
# TODO: NOT YET WORKING
